Konstantin8105/c4go

tests/function.c
types/cast.go

add test for NullPointer to function

---

tests/while.c
transpiler/branch.go

function createIfWithNotConditionAndBreak with type CallExpr

---

tests/stdio.c
transpiler/unary.go

add type ast.CharacterLiteral for transpileUnaryExprOrTypeTraitExpr

---

ast/var_decl.go
ast/var_decl_test.go

AST: VarDecl

---

preprocessor/preprocessor.go
tests/math.c

expression

---

README.md

minor typo fixes on README

---

ast/util.go

change tab to spaces

---

other_test.go
program/warnings.go

Test: add test kilo editor

---

main.go
program/warnings.go

GOPATH is empty

---

ast/annotate_attr.go
ast/annotate_attr_test.go
ast/ast.go
ast/position.go

ast: add AnnotateAttr

---

scripts/scripts.txt
tests/sizeof.c
tests/stdio.c
transpiler/value_to_pointer.go
types/sizeof.go

get sizeof for type : FILE *

---

ast/alloc_size_attr_test.go
ast/ast.go
ast/enable_if_attr.go
ast/enable_if_attr_test.go
ast/overloadable_attr.go
ast/overloadable_attr_test.go
ast/position.go

ast: add node for termux clang

---

README.md
program/program.go
scripts/neatroff.sh
scripts/scripts.txt
tests/stdarg.c
tests/stdio.c
transpiler/bind.go
transpiler/call.go
transpiler/declarations.go
transpiler/functions.go
transpiler/scope.go
transpiler/transpiler.go
transpiler/vaarg.go
transpiler/variables.go
types/cast.go
types/resolve.go

stdarg: va_list

---

ast/ast.go
ast/binary_conditional_operator.go
ast/binary_conditional_operator_test.go
ast/opaque_value_expr.go
ast/opaque_value_expr_test.go
ast/position.go
tests/ternary.c
transpiler/operators.go
transpiler/transpiler.go

ternary without middle case

---

scripts/nuklear.sh
scripts/redis.sh
scripts/scripts.sh
scripts/scripts.txt
transpiler/binary.go
transpiler/bind.go
transpiler/cast.go
transpiler/enum.go
transpiler/operators.go
transpiler/unary.go
transpiler/value_to_pointer.go
types/cast.go
util/goast.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e6b1a]
goroutine 1 [running]:
go/ast.(*UnaryExpr).End(0xc001aed640, 0x0)
/home/konstantin/Program/go/src/go/ast/ast.go:476 +0x2a
go/printer.(*printer).exprList(0xc005d49548, 0x0, 0xc001d28550, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0)
/home/konstantin/Program/go/src/go/printer/nodes.go:148 +0x23b
go/printer.(*printer).expr1(0xc005d49548, 0x7513c0, 0xc001cd7bc0, 0x0, 0x1)
/home/konstantin/Program/go/src/go/printer/nodes.go:893 +0x21aa
go/printer.(*printer).expr(0xc005d49548, 0x7513c0, 0xc001cd7bc0)
/home/konstantin/Program/go/src/go/printer/nodes.go:1001 +0x51
go/printer.(*printer).printNode(0xc005d49548, 0x6a7420, 0xc001cd7bc0, 0xc001cb1100, 0x1d) …
```

example: nuklear

---

main_test.go

Ignore os.Stderr for test with wrong ast

---

noarch/stdlib.go

Addresses the improvements mentioned by @JalonSolov in #160. Ran and passed all test suites.

stdlib.system: simplify output capture logic

---

ast/visibility_attr.go
ast/visibility_attr_test.go

VisibilityAttr: add Implicit

---

README.md
noarch/stdlib.go
tests/stdlib.c
transpiler/call.go

Add bsearch() function.
There is one last thing to-do: Handle the nil cast interface (There is a warning message for now).

Add bsearch() (#152)

---

README.md

Tested corrections and other clarity-related amendments to README.md.

Update README.md per issue #509

---

.dockerignore
Dockerfile
other_test.go

Docker: run c4go in docker
